export const BASE_CONCERTS = [
  {
    id: 'base-1',
    artist: 'The Midnight',
    opener: 'Nightly',
    venue: 'Red Rocks Amphitheatre',
    city: 'Morrison',
    country: 'USA',
    date: '2022-09-14',
    setTime: '20:30',
    ticketPrice: 59,
    festKey: '',
    favorite: 'star',
    pending: false,
    estimated: false,
    crew: ['Alex', 'Jordan'],
    notes: 'Perfect weather and synth-heavy encore.',
    type: 'concert',
  },
  {
    id: 'base-2',
    artist: 'Tame Impala',
    opener: 'Perfume Genius',
    venue: 'Madison Square Garden',
    city: 'New York',
    country: 'USA',
    date: '2023-03-10',
    setTime: '21:00',
    ticketPrice: 125,
    festKey: '',
    favorite: 'doublestar',
    pending: false,
    estimated: false,
    crew: ['Sam'],
    notes: 'Mind-blowing visuals.',
    type: 'concert',
  },
  {
    id: 'base-3',
    artist: 'The National / Phoebe Bridgers',
    opener: '',
    venue: 'Grant Park',
    city: 'Chicago',
    country: 'USA',
    date: '2023-08-03',
    setTime: '18:00',
    ticketPrice: 0,
    festKey: 'lolla-2023',
    favorite: 'none',
    pending: false,
    estimated: false,
    crew: ['Alex', 'Morgan'],
    notes: 'Festival day one.',
    type: 'festival',
  },
  {
    id: 'base-4',
    artist: 'Fred again..',
    opener: '',
    venue: 'Parc del Fòrum',
    city: 'Barcelona',
    country: 'Spain',
    date: '2024-06-01',
    setTime: '22:00',
    ticketPrice: 0,
    festKey: 'primavera-2024',
    favorite: 'star',
    pending: false,
    estimated: false,
    crew: ['Taylor'],
    notes: 'Late-night set at Primavera.',
    type: 'festival',
  },
  {
    id: 'base-5',
    artist: 'Chappell Roan',
    opener: '',
    venue: 'Anthem',
    city: 'Washington',
    country: 'USA',
    date: '2027-04-25',
    setTime: '',
    ticketPrice: 88,
    festKey: '',
    favorite: 'none',
    pending: true,
    estimated: true,
    crew: ['Jordan'],
    notes: 'Ticket purchased, time not announced.',
    type: 'concert',
  },
];

export const FESTIVALS = {
  'lolla-2023': {
    name: 'Lollapalooza 2023',
    days: [
      { label: 'Thu', artists: ['The National', 'Maggie Rogers', 'Rina Sawayama'] },
      { label: 'Fri', artists: ['Kendrick Lamar', 'The 1975'] },
    ],
  },
  'primavera-2024': {
    name: 'Primavera Sound 2024',
    days: [
      { label: 'Day 1', artists: ['Pulp', 'SZA', 'Lana Del Rey'] },
      { label: 'Day 2', artists: ['Fred again..', 'The National'] },
    ],
  },
};

export const ARTIST_ALIASES = {
  'the national': 'The National',
  'national': 'The National',
  'phoebe bridgers': 'Phoebe Bridgers',
  'boygenius': 'Phoebe Bridgers',
  'fred again': 'Fred again..',
  'fred again..': 'Fred again..',
};

export const EMPTY_ENTRY = {
  artist: '',
  opener: '',
  venue: '',
  city: '',
  country: '',
  date: '',
  setTime: '',
  ticketPrice: '',
  festKey: '',
  favorite: 'none',
  pending: false,
  estimated: false,
  crew: [],
  notes: '',
  type: 'concert',
};
